version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@1.0.53
  slack: circleci/slack@4.12.5

workflows:
  checkout-build-publish:
    jobs:
      - reporting/gradle_owasp_check:
          notify_slack: false
          context:
            - hmpps-reporting-common
            - hmpps-reporting-orb
          cache_key: "dpr-scheduled-lambda-build-cache-v3"
      - reporting/gradle_build_publish:
          tag: "21.0"
          app: hmpps-dpr-scheduled-dataset-lambda
          app_artifacts_directory: build/libs/
          bucket_prefix: dpr-artifact-store
          sync_args: "--exclude '*' --include '*-all*jar'"
          deploy_to_test: true # Deploy to Test Environment
          refresh_lambda: false
          notify_jira: true
          notify_slack: true
          channel: dpr_cicd_alerts
          command: jar shadowJar # Skip tests when building jar, they've already run
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
          ref: << pipeline.git.branch >><< pipeline.git.tag >>
          context:
            - hmpps-reporting-common
            - hmpps-reporting-orb
          cache_key: "dpr-scheduled-lambda-build-cache-v5"

  owasp-security:
    triggers:
      - schedule:
          cron: "30 6 * * *" ## Runs everyday at 7.30 AM UK TIME
          filters:
            branches:
              only:
                - main
    jobs:
      - reporting/gradle_owasp_check:
          notify_slack: true
          channel: dpr_cicd_alerts
          context:
            - hmpps-reporting-common
            - hmpps-reporting-orb
          cache_key: "dpr-owasp-scheduled-lambda-build-cache-v1"
