name: Add coverage to PR

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  coverage:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Calculate test coverage
        id: calculate-test-coverage
        run: |
          ./gradlew jacocoTestReport | tee logs.txt
#          grep 'Test Coverage:' logs.txt -A6 > message.txt

#      - name: PR comment
#        uses: thollander/actions-comment-pull-request@v2
#        with:
#          comment_tag: coverage
#          filePath: message.txt
